# Generated by Django 4.1.3 on 2022-11-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='product', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Feature', 'Feature'), ('Sale', 'Sale'), ('New', 'New')], max_length=10, verbose_name='Flag'),
        ),
    ]
