# Generated by Django 4.1.3 on 2022-11-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quan',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('New', 'New'), ('Feature', 'Feature'), ('Sale', 'Sale')], max_length=10, verbose_name='Flag'),
        ),
    ]
