# Generated by Django 4.1.3 on 2022-11-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_quan_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Feature', 'Feature'), ('Sale', 'Sale'), ('New', 'New')], max_length=10, verbose_name='Flag'),
        ),
    ]
